"""Nifty 500 universe.

Edit ``tickers`` below to add/remove symbols. Used by momentum_rs_lv_n500 and stock RRG.
"""

KEY = "n500"
LABEL = "Nifty 500"
DESCRIPTION = "Nifty 500 merged constituents"
BENCHMARK_NSE = "Nifty 500"

DEFAULT_VISIBLE = {
    "RELIANCE",
    "TCS",
    "HDFCBANK",
    "INFY",
    "ICICIBANK",
    "BHARTIARTL",
    "ITC",
    "SBIN",
    "HINDUNILVR",
    "KOTAKBANK",
    "LT",
    "AXISBANK",
    "MARUTI",
    "BAJFINANCE",
    "TITAN",
    "SUNPHARMA",
    "HCLTECH",
    "WIPRO",
    "ULTRACEMCO",
    "NESTLEIND",
}

# --- Ticker universe
tickers = [
    {'industry': 'Metals & Mining', 'marketcap': 'Nifty50', 'symbol': 'ADANIENT.NS'},
    {'industry': 'Services', 'marketcap': 'Nifty50', 'symbol': 'ADANIPORTS.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Nifty50', 'symbol': 'APOLLOHOSP.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Nifty50', 'symbol': 'ASIANPAINT.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Nifty50', 'symbol': 'AXISBANK.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Nifty50', 'symbol': 'BAJAJ-AUTO.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Nifty50', 'symbol': 'BAJFINANCE.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Nifty50', 'symbol': 'BAJAJFINSV.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Nifty50', 'symbol': 'BEL.NS'},
    {'industry': 'Telecommunication', 'marketcap': 'Nifty50', 'symbol': 'BHARTIARTL.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Nifty50', 'symbol': 'CIPLA.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Nifty50', 'symbol': 'COALINDIA.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Nifty50', 'symbol': 'DRREDDY.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Nifty50', 'symbol': 'EICHERMOT.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Nifty50', 'symbol': 'ETERNAL.NS'},
    {'industry': 'Construction Materials', 'marketcap': 'Nifty50', 'symbol': 'GRASIM.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Nifty50', 'symbol': 'HCLTECH.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Nifty50', 'symbol': 'HDFCBANK.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Nifty50', 'symbol': 'HDFCLIFE.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Nifty50', 'symbol': 'HINDALCO.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Nifty50', 'symbol': 'HINDUNILVR.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Nifty50', 'symbol': 'ICICIBANK.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Nifty50', 'symbol': 'ITC.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Nifty50', 'symbol': 'INFY.NS'},
    {'industry': 'Services', 'marketcap': 'Nifty50', 'symbol': 'INDIGO.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Nifty50', 'symbol': 'JSWSTEEL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Nifty50', 'symbol': 'JIOFIN.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Nifty50', 'symbol': 'KOTAKBANK.NS'},
    {'industry': 'Construction', 'marketcap': 'Nifty50', 'symbol': 'LT.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Nifty50', 'symbol': 'M&M.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Nifty50', 'symbol': 'MARUTI.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Nifty50', 'symbol': 'MAXHEALTH.NS'},
    {'industry': 'Power', 'marketcap': 'Nifty50', 'symbol': 'NTPC.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Nifty50', 'symbol': 'NESTLEIND.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Nifty50', 'symbol': 'ONGC.NS'},
    {'industry': 'Power', 'marketcap': 'Nifty50', 'symbol': 'POWERGRID.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Nifty50', 'symbol': 'RELIANCE.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Nifty50', 'symbol': 'SBILIFE.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Nifty50', 'symbol': 'SHRIRAMFIN.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Nifty50', 'symbol': 'SBIN.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Nifty50', 'symbol': 'SUNPHARMA.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Nifty50', 'symbol': 'TCS.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Nifty50', 'symbol': 'TATACONSUM.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Nifty50', 'symbol': 'TMPV.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Nifty50', 'symbol': 'TATASTEEL.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Nifty50', 'symbol': 'TECHM.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Nifty50', 'symbol': 'TITAN.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Nifty50', 'symbol': 'TRENT.NS'},
    {'industry': 'Construction Materials', 'marketcap': 'Nifty50', 'symbol': 'ULTRACEMCO.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Nifty50', 'symbol': 'WIPRO.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Next50', 'symbol': 'ABB.NS'},
    {'industry': 'Power', 'marketcap': 'Next50', 'symbol': 'ADANIENSOL.NS'},
    {'industry': 'Power', 'marketcap': 'Next50', 'symbol': 'ADANIGREEN.NS'},
    {'industry': 'Power', 'marketcap': 'Next50', 'symbol': 'ADANIPOWER.NS'},
    {'industry': 'Construction Materials', 'marketcap': 'Next50', 'symbol': 'AMBUJACEM.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Next50', 'symbol': 'DMART.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Next50', 'symbol': 'BAJAJHLDNG.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Next50', 'symbol': 'BANKBARODA.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Next50', 'symbol': 'BPCL.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Next50', 'symbol': 'BOSCHLTD.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Next50', 'symbol': 'BRITANNIA.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Next50', 'symbol': 'CGPOWER.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Next50', 'symbol': 'CANBK.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Next50', 'symbol': 'CHOLAFIN.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Next50', 'symbol': 'CUMMINSIND.NS'},
    {'industry': 'Realty', 'marketcap': 'Next50', 'symbol': 'DLF.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Next50', 'symbol': 'DIVISLAB.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Next50', 'symbol': 'GAIL.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Next50', 'symbol': 'GODREJCP.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Next50', 'symbol': 'HDFCAMC.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Next50', 'symbol': 'HAL.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Next50', 'symbol': 'HINDZINC.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Next50', 'symbol': 'HYUNDAI.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Next50', 'symbol': 'INDHOTEL.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Next50', 'symbol': 'IOC.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Next50', 'symbol': 'IRFC.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Next50', 'symbol': 'JINDALSTEL.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Next50', 'symbol': 'LTM.NS'},
    {'industry': 'Realty', 'marketcap': 'Next50', 'symbol': 'LODHA.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Next50', 'symbol': 'MAZDOCK.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Next50', 'symbol': 'MUTHOOTFIN.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Next50', 'symbol': 'PIDILITIND.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Next50', 'symbol': 'PFC.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Next50', 'symbol': 'PNB.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Next50', 'symbol': 'RECLTD.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Next50', 'symbol': 'MOTHERSON.NS'},
    {'industry': 'Construction Materials', 'marketcap': 'Next50', 'symbol': 'SHREECEM.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Next50', 'symbol': 'ENRIN.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Next50', 'symbol': 'SIEMENS.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Next50', 'symbol': 'SOLARINDS.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Next50', 'symbol': 'TVSMOTOR.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Next50', 'symbol': 'TATACAP.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Next50', 'symbol': 'TMCV.NS'},
    {'industry': 'Power', 'marketcap': 'Next50', 'symbol': 'TATAPOWER.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Next50', 'symbol': 'TORNTPHARM.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Next50', 'symbol': 'UNIONBANK.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Next50', 'symbol': 'UNITDSPR.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Next50', 'symbol': 'VBL.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Next50', 'symbol': 'VEDL.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Next50', 'symbol': 'ZYDUSLIFE.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': '360ONE.NS'},
    {'industry': 'Diversified', 'marketcap': 'Midcap', 'symbol': '3MINDIA.NS'},
    {'industry': 'Construction Materials', 'marketcap': 'Midcap', 'symbol': 'ACC.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'AIAENG.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'APLAPOLLO.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'AUBANK.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Midcap', 'symbol': 'AWL.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'ABBOTINDIA.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Midcap', 'symbol': 'ATGL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'ABCAPITAL.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'AJANTPHARM.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'ALKEM.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'ANTHEM.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'APARINDS.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'APOLLOTYRE.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'ASHOKLEY.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'ASTRAL.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'AUROPHARMA.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'AIIL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'BSE.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'BAJAJHFL.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'BALKRISIND.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'BANKINDIA.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'MAHABANK.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Midcap', 'symbol': 'BERGEPAINT.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'BDL.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'BHARATFORG.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'BHEL.NS'},
    {'industry': 'Telecommunication', 'marketcap': 'Midcap', 'symbol': 'BHARTIHEXA.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'GROWW.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'BIOCON.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Midcap', 'symbol': 'BLUESTARCO.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'CRISIL.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'COCHINSHIP.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'COFORGE.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Midcap', 'symbol': 'COLPAL.NS'},
    {'industry': 'Services', 'marketcap': 'Midcap', 'symbol': 'CONCOR.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Midcap', 'symbol': 'COROMANDEL.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Midcap', 'symbol': 'DABUR.NS'},
    {'industry': 'Construction Materials', 'marketcap': 'Midcap', 'symbol': 'DALBHARAT.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Midcap', 'symbol': 'DIXON.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'ENDURANCE.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'ESCORTS.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'EXIDEIND.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Midcap', 'symbol': 'NYKAA.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'FEDERALBNK.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'FORTIS.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'GVT&D.NS'},
    {'industry': 'Services', 'marketcap': 'Midcap', 'symbol': 'GMRAIRPORT.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'GICRE.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'GLAXO.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'GLENMARK.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'MEDANTA.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Midcap', 'symbol': 'GODFRYPHLP.NS'},
    {'industry': 'Diversified', 'marketcap': 'Midcap', 'symbol': 'GODREJIND.NS'},
    {'industry': 'Realty', 'marketcap': 'Midcap', 'symbol': 'GODREJPROP.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Midcap', 'symbol': 'FLUOROCHEM.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'HDBFS.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Midcap', 'symbol': 'HAVELLS.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'HEROMOTOCO.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'HEXT.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Midcap', 'symbol': 'HINDPETRO.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'POWERINDIA.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'HONAUT.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'HUDCO.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'ICICIGI.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'ICICIAMC.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'ICICIPRULI.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'IDFCFIRSTB.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Midcap', 'symbol': 'ITCHOTELS.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'INDIANB.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Midcap', 'symbol': 'IRCTC.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'IREDA.NS'},
    {'industry': 'Telecommunication', 'marketcap': 'Midcap', 'symbol': 'INDUSTOWER.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'INDUSINDBK.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Midcap', 'symbol': 'NAUKRI.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'IPCALAB.NS'},
    {'industry': 'Construction Materials', 'marketcap': 'Midcap', 'symbol': 'JKCEMENT.NS'},
    {'industry': 'Power', 'marketcap': 'Midcap', 'symbol': 'JSWENERGY.NS'},
    {'industry': 'Services', 'marketcap': 'Midcap', 'symbol': 'JSWINFRA.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Midcap', 'symbol': 'JSL.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Midcap', 'symbol': 'JUBLFOOD.NS'},
    {'industry': 'Textiles', 'marketcap': 'Midcap', 'symbol': 'KPRMILL.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'KEI.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'KPITTECH.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Midcap', 'symbol': 'KALYANKJIL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'LTF.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'LTTS.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Midcap', 'symbol': 'LGEINDIA.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'LICHSGFIN.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'LAURUSLABS.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Midcap', 'symbol': 'LENSKART.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'LICI.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Midcap', 'symbol': 'LINDEINDIA.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Midcap', 'symbol': 'LLOYDSME.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'LUPIN.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'MRF.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'M&MFIN.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'MANKIND.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Midcap', 'symbol': 'MARICO.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'MFSL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'MOTILALOFS.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'MPHASIS.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'MCX.NS'},
    {'industry': 'Power', 'marketcap': 'Midcap', 'symbol': 'NHPC.NS'},
    {'industry': 'Power', 'marketcap': 'Midcap', 'symbol': 'NLCINDIA.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Midcap', 'symbol': 'NMDC.NS'},
    {'industry': 'Power', 'marketcap': 'Midcap', 'symbol': 'NTPCGREEN.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Midcap', 'symbol': 'NATIONALUM.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'NAM-INDIA.NS'},
    {'industry': 'Realty', 'marketcap': 'Midcap', 'symbol': 'OBEROIRLTY.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Midcap', 'symbol': 'OIL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'PAYTM.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'OFSS.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'POLICYBZR.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Midcap', 'symbol': 'PIIND.NS'},
    {'industry': 'Textiles', 'marketcap': 'Midcap', 'symbol': 'PAGEIND.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Midcap', 'symbol': 'PATANJALI.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'PERSISTENT.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Midcap', 'symbol': 'PETRONET.NS'},
    {'industry': 'Realty', 'marketcap': 'Midcap', 'symbol': 'PHOENIXLTD.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'POLYCAB.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'PREMIERENE.NS'},
    {'industry': 'Realty', 'marketcap': 'Midcap', 'symbol': 'PRESTIGE.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Midcap', 'symbol': 'RADICO.NS'},
    {'industry': 'Construction', 'marketcap': 'Midcap', 'symbol': 'RVNL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'SBICARD.NS'},
    {'industry': 'Power', 'marketcap': 'Midcap', 'symbol': 'SJVN.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Midcap', 'symbol': 'SRF.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'SCHAEFFLER.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Midcap', 'symbol': 'SAIL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'SUNDARMFIN.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'SUPREMEIND.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'SUZLON.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Midcap', 'symbol': 'SWIGGY.NS'},
    {'industry': 'Telecommunication', 'marketcap': 'Midcap', 'symbol': 'TATACOMM.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'TATAELXSI.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'TATAINVEST.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'NIACL.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'THERMAX.NS'},
    {'industry': 'Power', 'marketcap': 'Midcap', 'symbol': 'TORNTPOWER.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'TIINDIA.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'UNOMINDA.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Midcap', 'symbol': 'UPL.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Midcap', 'symbol': 'UBL.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Midcap', 'symbol': 'VMM.NS'},
    {'industry': 'Telecommunication', 'marketcap': 'Midcap', 'symbol': 'IDEA.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Midcap', 'symbol': 'VOLTAS.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'WAAREEENER.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'YESBANK.NS'},
    {'industry': 'Power', 'marketcap': 'Smallcap', 'symbol': 'ACMESOLAR.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'AADHARHFC.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'AARTIIND.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'AAVAS.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'ACE.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'ACUTAAS.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'ABFRL.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'ABLBL.NS'},
    {'industry': 'Realty', 'marketcap': 'Smallcap', 'symbol': 'ABREL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'ABSLAMC.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'CPPLUS.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Smallcap', 'symbol': 'AEGISLOG.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Smallcap', 'symbol': 'AEGISVOPAK.NS'},
    {'industry': 'Construction', 'marketcap': 'Smallcap', 'symbol': 'AFCONS.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'AFFLE.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'ABDL.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'ARE&M.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Smallcap', 'symbol': 'AMBER.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'ANANDRATHI.NS'},
    {'industry': 'Realty', 'marketcap': 'Smallcap', 'symbol': 'ANANTRAJ.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'ANGELONE.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'ANURAS.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'APTUS.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'ASAHIINDIA.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'ASTERDM.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'ATHERENERG.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'ATUL.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'BEML.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'BLS.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'BALRAMCHIN.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'BANDHANBNK.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Smallcap', 'symbol': 'BATAINDIA.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'BAYERCROP.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'BELRISE.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'BIKAJI.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'BSOFT.NS'},
    {'industry': 'Services', 'marketcap': 'Smallcap', 'symbol': 'BLUEDART.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'BLUEJET.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'BBTC.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'FIRSTCRY.NS'},
    {'industry': 'Realty', 'marketcap': 'Smallcap', 'symbol': 'BRIGADE.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'MAPMYINDIA.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'CCL.NS'},
    {'industry': 'Power', 'marketcap': 'Smallcap', 'symbol': 'CESC.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'CIEINDIA.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'CANFINHOME.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'CANHLIFE.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'CAPLIPOINT.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'CGCL.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'CARBORUNIV.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'CARTRADE.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Smallcap', 'symbol': 'CASTROLIND.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'CEATLTD.NS'},
    {'industry': 'Construction', 'marketcap': 'Smallcap', 'symbol': 'CEMPRO.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'CENTRALBK.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'CDSL.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'CHALET.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'CHAMBLFERT.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Smallcap', 'symbol': 'CHENNPETRO.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'CHOICEIN.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'CHOLAHLDNG.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'CUB.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'CLEAN.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'COHANCE.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'CAMS.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'CONCORDBIO.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'CRAFTSMAN.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'CREDITACC.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Smallcap', 'symbol': 'CROMPTON.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'CYIENT.NS'},
    {'industry': 'Diversified', 'marketcap': 'Smallcap', 'symbol': 'DCMSHRIRAM.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'DOMS.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'DATAPATTNS.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'DEEPAKFERT.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'DEEPAKNTR.NS'},
    {'industry': 'Services', 'marketcap': 'Smallcap', 'symbol': 'DELHIVERY.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'DEVYANI.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'LALPATHLAB.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'EIDPARRY.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'EIHOTEL.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'ELECON.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'ELGIEQUIP.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'EMAMILTD.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'EMCURE.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'EMMVEE.NS'},
    {'industry': 'Construction', 'marketcap': 'Smallcap', 'symbol': 'ENGINERSIN.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'ERIS.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'FACT.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'FINCABLES.NS'},
    {'industry': 'Services', 'marketcap': 'Smallcap', 'symbol': 'FSL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'FIVESTAR.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'FORCEMOT.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'GABRIEL.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'GALLANTT.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'GRSE.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'GILLETTE.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'GLAND.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'GODIGIT.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'GPIL.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'GRANULES.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'GRAPHITE.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Smallcap', 'symbol': 'GRAVITA.NS'},
    {'industry': 'Services', 'marketcap': 'Smallcap', 'symbol': 'GESHIP.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Smallcap', 'symbol': 'GMDCLTD.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'HEG.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'HBLENGINE.NS'},
    {'industry': 'Telecommunication', 'marketcap': 'Smallcap', 'symbol': 'HFCL.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'HSCL.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Smallcap', 'symbol': 'HINDCOPPER.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'HOMEFIRST.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'HONASA.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'IDBI.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'IFCI.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'IIFL.NS'},
    {'industry': 'Construction', 'marketcap': 'Smallcap', 'symbol': 'IRB.NS'},
    {'industry': 'Construction', 'marketcap': 'Smallcap', 'symbol': 'IRCON.NS'},
    {'industry': 'Telecommunication', 'marketcap': 'Smallcap', 'symbol': 'ITI.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'INDGN.NS'},
    {'industry': 'Construction Materials', 'marketcap': 'Smallcap', 'symbol': 'INDIACEM.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'INDIAMART.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'IEX.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'IOB.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Smallcap', 'symbol': 'IGL.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'INOXWIND.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'INTELLECT.NS'},
    {'industry': 'Services', 'marketcap': 'Smallcap', 'symbol': 'IGIL.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'IKS.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'JBCHEPHARM.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'JBMA.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'JKTYRE.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'JMFINANCIL.NS'},
    {'industry': 'Construction Materials', 'marketcap': 'Smallcap', 'symbol': 'JSWCEMENT.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Smallcap', 'symbol': 'JSWDULUX.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Smallcap', 'symbol': 'JAINREC.NS'},
    {'industry': 'Power', 'marketcap': 'Smallcap', 'symbol': 'JPPOWER.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'J&KBANK.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'JINDALSAW.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'JUBLINGREA.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'JUBLPHARMA.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'JWL.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'JYOTICNC.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Smallcap', 'symbol': 'KAJARIACER.NS'},
    {'industry': 'Construction', 'marketcap': 'Smallcap', 'symbol': 'KPIL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'KARURVYSYA.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'KAYNES.NS'},
    {'industry': 'Construction', 'marketcap': 'Smallcap', 'symbol': 'KEC.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'KFINTECH.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'KIRLOSENG.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'KIMS.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'LTFOODS.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'LATENTVIEW.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'THELEELA.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'LEMONTREE.NS'},
    {'industry': 'Services', 'marketcap': 'Smallcap', 'symbol': 'MMTC.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Smallcap', 'symbol': 'MGL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'MANAPPURAM.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Smallcap', 'symbol': 'MRPL.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'MEESHO.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'MINDACORP.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'MSUMI.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'NATCOPHARM.NS'},
    {'industry': 'Construction', 'marketcap': 'Smallcap', 'symbol': 'NBCC.NS'},
    {'industry': 'Construction', 'marketcap': 'Smallcap', 'symbol': 'NCC.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Smallcap', 'symbol': 'NSLNISP.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'NH.NS'},
    {'industry': 'Power', 'marketcap': 'Smallcap', 'symbol': 'NAVA.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'NAVINFLUOR.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'NETWEB.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'NEULANDLAB.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'NEWGEN.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'NIVABUPA.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'NUVAMA.NS'},
    {'industry': 'Construction Materials', 'marketcap': 'Smallcap', 'symbol': 'NUVOCO.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'OLAELEC.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'OLECTRA.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'ONESOURCE.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'PCBL.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Smallcap', 'symbol': 'PGEL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'PNBHOUSING.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'PTCIL.NS'},
    {'industry': 'Media Entertainment & Publication', 'marketcap': 'Smallcap', 'symbol': 'PVRINOX.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'PARADEEP.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'PFIZER.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'PWL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'PINELABS.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'PIRAMALFIN.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'PPLPHARMA.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'POLYMED.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'POONAWALLA.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'RRKABEL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'RBLBANK.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'RHIM.NS'},
    {'industry': 'Construction', 'marketcap': 'Smallcap', 'symbol': 'RITES.NS'},
    {'industry': 'Telecommunication', 'marketcap': 'Smallcap', 'symbol': 'RAILTEL.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'RAINBOW.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'RKFORGE.NS'},
    {'industry': 'Services', 'marketcap': 'Smallcap', 'symbol': 'REDINGTON.NS'},
    {'industry': 'Power', 'marketcap': 'Smallcap', 'symbol': 'RPOWER.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'SBFC.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'SAGILITY.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'SAILIFE.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'SAMMAANCAP.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'SAPPHIRE.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Smallcap', 'symbol': 'SARDAEN.NS'},
    {'industry': 'Media Entertainment & Publication', 'marketcap': 'Smallcap', 'symbol': 'SAREGAMA.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'SCHNEIDER.NS'},
    {'industry': 'Services', 'marketcap': 'Smallcap', 'symbol': 'SCI.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'SHYAMMETL.NS'},
    {'industry': 'Realty', 'marketcap': 'Smallcap', 'symbol': 'SIGNATURE.NS'},
    {'industry': 'Realty', 'marketcap': 'Smallcap', 'symbol': 'SOBHA.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'SONACOMS.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'SONATSOFTW.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'STARHEALTH.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'SUMICHEM.NS'},
    {'industry': 'Media Entertainment & Publication', 'marketcap': 'Smallcap', 'symbol': 'SUNTV.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'SPLPETRO.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'SWANCORP.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'SYNGENE.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'SYRMA.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'TBOTEK.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'TATACHEM.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'TATATECH.NS'},
    {'industry': 'Telecommunication', 'marketcap': 'Smallcap', 'symbol': 'TTML.NS'},
    {'industry': 'Construction', 'marketcap': 'Smallcap', 'symbol': 'TECHNOE.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'TEGA.NS'},
    {'industry': 'Telecommunication', 'marketcap': 'Smallcap', 'symbol': 'TEJASNET.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'TENNIND.NS'},
    {'industry': 'Construction Materials', 'marketcap': 'Smallcap', 'symbol': 'RAMCOCEM.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'TIMKEN.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'TITAGARH.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'TARIL.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'TRAVELFOOD.NS'},
    {'industry': 'Textiles', 'marketcap': 'Smallcap', 'symbol': 'TRIDENT.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'TRITURBINE.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'UCOBANK.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'UTIAMC.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'URBANCO.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'USHAMART.NS'},
    {'industry': 'Textiles', 'marketcap': 'Smallcap', 'symbol': 'VTL.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'VIJAYA.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'WELCORP.NS'},
    {'industry': 'Textiles', 'marketcap': 'Smallcap', 'symbol': 'WELSPUNLIV.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Smallcap', 'symbol': 'WHIRLPOOL.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'WOCKPHARMA.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'ZFCVINDIA.NS'},
    {'industry': 'Media Entertainment & Publication', 'marketcap': 'Smallcap', 'symbol': 'ZEEL.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'ZENTEC.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'ZENSARTECH.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'ZYDUSWELL.NS'},
    {'industry': 'Services', 'marketcap': 'Smallcap', 'symbol': 'ECLERX.NS'},
]

# --- end ticker universe ---
