"""Nifty LargeMidcap 250.

Edit ``tickers`` below to add/remove symbols. Used by momentum_rs_stocks.py and stock RRG.
"""

KEY = "nifty_largemidcap"
LABEL = "Nifty LargeMidcap 250"
DESCRIPTION = "Nifty LargeMidcap 250 constituents"
BENCHMARK_NSE = "Nifty LargeMidcap 250"

DEFAULT_VISIBLE = {
    "RELIANCE",
    "TCS",
    "HDFCBANK",
    "INFY",
    "ICICIBANK",
    "BHARTIARTL",
    "ITC",
    "SBIN",
    "HINDUNILVR",
    "KOTAKBANK",
    "LT",
    "AXISBANK",
    "MARUTI",
    "BAJFINANCE",
    "TITAN",
    "SUNPHARMA",
    "HCLTECH",
    "WIPRO",
    "ULTRACEMCO",
    "NESTLEIND",
}

# --- Ticker universe
tickers = [
    {'industry': 'Financial Services', 'symbol': '360ONE.NS'},
    {'industry': 'Diversified', 'symbol': '3MINDIA.NS'},
    {'industry': 'Commodities', 'symbol': 'AARTIIND.NS'},
    {'industry': 'Capital Goods', 'symbol': 'ABB.NS'},
    {'industry': 'Healthcare', 'symbol': 'ABBOTINDIA.NS'},
    {'industry': 'Construction Materials', 'symbol': 'ACC.NS'},
    {'industry': 'Power', 'symbol': 'ADANIENSOL.NS'},
    {'industry': 'Metals & Mining', 'symbol': 'ADANIENT.NS'},
    {'industry': 'Power', 'symbol': 'ADANIGREEN.NS'},
    {'industry': 'Services', 'symbol': 'ADANIPORTS.NS'},
    {'industry': 'Power', 'symbol': 'ADANIPOWER.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'symbol': 'ATGL.NS'},
    {'industry': 'Financial Services', 'symbol': 'ABCAPITAL.NS'},
    {'industry': 'Energy', 'symbol': 'AEGISVOPAK.NS'},
    {'industry': 'Capital Goods', 'symbol': 'AIAENG.NS'},
    {'industry': 'Healthcare', 'symbol': 'AJANTPHARM.NS'},
    {'industry': 'Healthcare', 'symbol': 'ALKEM.NS'},
    {'industry': 'Construction Materials', 'symbol': 'AMBUJACEM.NS'},
    {'industry': 'Healthcare', 'symbol': 'ANTHEM.NS'},
    {'industry': 'Capital Goods', 'symbol': 'APLAPOLLO.NS'},
    {'industry': 'Healthcare', 'symbol': 'APOLLOHOSP.NS'},
    {'industry': 'Capital Goods', 'symbol': 'ASHOKLEY.NS'},
    {'industry': 'Consumer Durables', 'symbol': 'ASIANPAINT.NS'},
    {'industry': 'Capital Goods', 'symbol': 'ASTRAL.NS'},
    {'industry': 'Financial Services', 'symbol': 'AUBANK.NS'},
    {'industry': 'Healthcare', 'symbol': 'AUROPHARMA.NS'},
    {'industry': 'Consumer Services', 'symbol': 'DMART.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'AWL.NS'},
    {'industry': 'Financial Services', 'symbol': 'AXISBANK.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'BAJAJ-AUTO.NS'},
    {'industry': 'Financial Services', 'symbol': 'BAJFINANCE.NS'},
    {'industry': 'Financial Services', 'symbol': 'BAJAJFINSV.NS'},
    {'industry': 'Financial Services', 'symbol': 'BAJAJHLDNG.NS'},
    {'industry': 'Financial Services', 'symbol': 'BAJAJHFL.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'BALKRISIND.NS'},
    {'industry': 'Financial Services', 'symbol': 'BANDHANBNK.NS'},
    {'industry': 'Financial Services', 'symbol': 'BANKBARODA.NS'},
    {'industry': 'Financial Services', 'symbol': 'BANKINDIA.NS'},
    {'industry': 'Financial Services', 'symbol': 'MAHABANK.NS'},
    {'industry': 'Commodities', 'symbol': 'BAYERCROP.NS'},
    {'industry': 'Consumer Durables', 'symbol': 'BERGEPAINT.NS'},
    {'industry': 'Capital Goods', 'symbol': 'BDL.NS'},
    {'industry': 'Capital Goods', 'symbol': 'BEL.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'BHARATFORG.NS'},
    {'industry': 'Capital Goods', 'symbol': 'BHEL.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'symbol': 'BPCL.NS'},
    {'industry': 'Telecommunication', 'symbol': 'BHARTIARTL.NS'},
    {'industry': 'Telecommunication', 'symbol': 'BHARTIHEXA.NS'},
    {'industry': 'Financial Services', 'symbol': 'GROWW.NS'},
    {'industry': 'Healthcare', 'symbol': 'BIOCON.NS'},
    {'industry': 'Consumer Durables', 'symbol': 'BLUESTARCO.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'BOSCHLTD.NS'},
    {'industry': 'Consumer Discretionary', 'symbol': 'FIRSTCRY.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'BRITANNIA.NS'},
    {'industry': 'Financial Services', 'symbol': 'CANBK.NS'},
    {'industry': 'Energy', 'symbol': 'CASTROLIND.NS'},
    {'industry': 'Financial Services', 'symbol': 'CENTRALBK.NS'},
    {'industry': 'Capital Goods', 'symbol': 'CGPOWER.NS'},
    {'industry': 'Financial Services', 'symbol': 'CHOLAFIN.NS'},
    {'industry': 'Healthcare', 'symbol': 'CIPLA.NS'},
    {'industry': 'Commodities', 'symbol': 'CLEAN.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'symbol': 'COALINDIA.NS'},
    {'industry': 'Capital Goods', 'symbol': 'COCHINSHIP.NS'},
    {'industry': 'Information Technology', 'symbol': 'COFORGE.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'COLPAL.NS'},
    {'industry': 'Services', 'symbol': 'CONCOR.NS'},
    {'industry': 'Chemicals', 'symbol': 'COROMANDEL.NS'},
    {'industry': 'Financial Services', 'symbol': 'CRISIL.NS'},
    {'industry': 'Consumer Discretionary', 'symbol': 'CROMPTON.NS'},
    {'industry': 'Capital Goods', 'symbol': 'CUMMINSIND.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'DABUR.NS'},
    {'industry': 'Construction Materials', 'symbol': 'DALBHARAT.NS'},
    {'industry': 'Commodities', 'symbol': 'DEEPAKNTR.NS'},
    {'industry': 'Services', 'symbol': 'DELHIVERY.NS'},
    {'industry': 'Healthcare', 'symbol': 'DIVISLAB.NS'},
    {'industry': 'Consumer Durables', 'symbol': 'DIXON.NS'},
    {'industry': 'Realty', 'symbol': 'DLF.NS'},
    {'industry': 'Healthcare', 'symbol': 'DRREDDY.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'EICHERMOT.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'EMAMILTD.NS'},
    {'industry': 'Healthcare', 'symbol': 'EMCURE.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'ENDURANCE.NS'},
    {'industry': 'Capital Goods', 'symbol': 'ESCORTS.NS'},
    {'industry': 'Consumer Services', 'symbol': 'ETERNAL.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'EXIDEIND.NS'},
    {'industry': 'Financial Services', 'symbol': 'FEDERALBNK.NS'},
    {'industry': 'Healthcare', 'symbol': 'FORTIS.NS'},
    {'industry': 'Consumer Services', 'symbol': 'NYKAA.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'symbol': 'GAIL.NS'},
    {'industry': 'Capital Goods', 'symbol': 'GVT&D.NS'},
    {'industry': 'Financial Services', 'symbol': 'GICRE.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'GILLETTE.NS'},
    {'industry': 'Healthcare', 'symbol': 'GLAND.NS'},
    {'industry': 'Healthcare', 'symbol': 'GLAXO.NS'},
    {'industry': 'Healthcare', 'symbol': 'GLENMARK.NS'},
    {'industry': 'Services', 'symbol': 'GMRAIRPORT.NS'},
    {'industry': 'Financial Services', 'symbol': 'GODIGIT.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'GODREJCP.NS'},
    {'industry': 'Diversified', 'symbol': 'GODREJIND.NS'},
    {'industry': 'Realty', 'symbol': 'GODREJPROP.NS'},
    {'industry': 'Construction Materials', 'symbol': 'GRASIM.NS'},
    {'industry': 'Chemicals', 'symbol': 'FLUOROCHEM.NS'},
    {'industry': 'Consumer Durables', 'symbol': 'HAVELLS.NS'},
    {'industry': 'Information Technology', 'symbol': 'HCLTECH.NS'},
    {'industry': 'Financial Services', 'symbol': 'HDBFS.NS'},
    {'industry': 'Financial Services', 'symbol': 'HDFCAMC.NS'},
    {'industry': 'Financial Services', 'symbol': 'HDFCBANK.NS'},
    {'industry': 'Financial Services', 'symbol': 'HDFCLIFE.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'HEROMOTOCO.NS'},
    {'industry': 'Information Technology', 'symbol': 'HEXT.NS'},
    {'industry': 'Metals & Mining', 'symbol': 'HINDALCO.NS'},
    {'industry': 'Capital Goods', 'symbol': 'HAL.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'symbol': 'HINDPETRO.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'HINDUNILVR.NS'},
    {'industry': 'Metals & Mining', 'symbol': 'HINDZINC.NS'},
    {'industry': 'Capital Goods', 'symbol': 'POWERINDIA.NS'},
    {'industry': 'Capital Goods', 'symbol': 'HONAUT.NS'},
    {'industry': 'Financial Services', 'symbol': 'HUDCO.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'HYUNDAI.NS'},
    {'industry': 'Financial Services', 'symbol': 'ICICIBANK.NS'},
    {'industry': 'Financial Services', 'symbol': 'ICICIGI.NS'},
    {'industry': 'Financial Services', 'symbol': 'ICICIAMC.NS'},
    {'industry': 'Financial Services', 'symbol': 'ICICIPRULI.NS'},
    {'industry': 'Financial Services', 'symbol': 'IDBI.NS'},
    {'industry': 'Financial Services', 'symbol': 'IDFCFIRSTB.NS'},
    {'industry': 'Financial Services', 'symbol': 'INDIANB.NS'},
    {'industry': 'Consumer Services', 'symbol': 'INDHOTEL.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'symbol': 'IOC.NS'},
    {'industry': 'Financial Services', 'symbol': 'IOB.NS'},
    {'industry': 'Consumer Services', 'symbol': 'IRCTC.NS'},
    {'industry': 'Financial Services', 'symbol': 'IRFC.NS'},
    {'industry': 'Financial Services', 'symbol': 'IREDA.NS'},
    {'industry': 'Energy', 'symbol': 'IGL.NS'},
    {'industry': 'Telecommunication', 'symbol': 'INDUSTOWER.NS'},
    {'industry': 'Financial Services', 'symbol': 'INDUSINDBK.NS'},
    {'industry': 'Consumer Services', 'symbol': 'NAUKRI.NS'},
    {'industry': 'Information Technology', 'symbol': 'INFY.NS'},
    {'industry': 'Services', 'symbol': 'INDIGO.NS'},
    {'industry': 'Information Technology', 'symbol': 'IKS.NS'},
    {'industry': 'Healthcare', 'symbol': 'IPCALAB.NS'},
    {'industry': 'Consumer Services', 'symbol': 'ITCHOTELS.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'ITC.NS'},
    {'industry': 'Construction Materials', 'symbol': 'JKCEMENT.NS'},
    {'industry': 'Metals & Mining', 'symbol': 'JSL.NS'},
    {'industry': 'Metals & Mining', 'symbol': 'JINDALSTEL.NS'},
    {'industry': 'Financial Services', 'symbol': 'JIOFIN.NS'},
    {'industry': 'Power', 'symbol': 'JSWENERGY.NS'},
    {'industry': 'Services', 'symbol': 'JSWINFRA.NS'},
    {'industry': 'Metals & Mining', 'symbol': 'JSWSTEEL.NS'},
    {'industry': 'Consumer Services', 'symbol': 'JUBLFOOD.NS'},
    {'industry': 'Consumer Durables', 'symbol': 'KALYANKJIL.NS'},
    {'industry': 'Industrials', 'symbol': 'KAYNES.NS'},
    {'industry': 'Capital Goods', 'symbol': 'KEI.NS'},
    {'industry': 'Financial Services', 'symbol': 'KOTAKBANK.NS'},
    {'industry': 'Information Technology', 'symbol': 'KPITTECH.NS'},
    {'industry': 'Financial Services', 'symbol': 'LTF.NS'},
    {'industry': 'Information Technology', 'symbol': 'LTTS.NS'},
    {'industry': 'Construction', 'symbol': 'LT.NS'},
    {'industry': 'Healthcare', 'symbol': 'LAURUSLABS.NS'},
    {'industry': 'Consumer Services', 'symbol': 'LENSKART.NS'},
    {'industry': 'Consumer Durables', 'symbol': 'LGEINDIA.NS'},
    {'industry': 'Financial Services', 'symbol': 'LICHSGFIN.NS'},
    {'industry': 'Financial Services', 'symbol': 'LICI.NS'},
    {'industry': 'Chemicals', 'symbol': 'LINDEINDIA.NS'},
    {'industry': 'Metals & Mining', 'symbol': 'LLOYDSME.NS'},
    {'industry': 'Realty', 'symbol': 'LODHA.NS'},
    {'industry': 'Information Technology', 'symbol': 'LTM.NS'},
    {'industry': 'Healthcare', 'symbol': 'LUPIN.NS'},
    {'industry': 'Financial Services', 'symbol': 'M&MFIN.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'M&M.NS'},
    {'industry': 'Healthcare', 'symbol': 'MANKIND.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'MARICO.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'MARUTI.NS'},
    {'industry': 'Financial Services', 'symbol': 'MFSL.NS'},
    {'industry': 'Healthcare', 'symbol': 'MAXHEALTH.NS'},
    {'industry': 'Capital Goods', 'symbol': 'MAZDOCK.NS'},
    {'industry': 'Consumer Discretionary', 'symbol': 'MEESHO.NS'},
    {'industry': 'Financial Services', 'symbol': 'MOTILALOFS.NS'},
    {'industry': 'Information Technology', 'symbol': 'MPHASIS.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'MRF.NS'},
    {'industry': 'Financial Services', 'symbol': 'MUTHOOTFIN.NS'},
    {'industry': 'Metals & Mining', 'symbol': 'NATIONALUM.NS'},
    {'industry': 'Financial Services', 'symbol': 'CDSL.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'NESTLEIND.NS'},
    {'industry': 'Power', 'symbol': 'NHPC.NS'},
    {'industry': 'Financial Services', 'symbol': 'NAM-INDIA.NS'},
    {'industry': 'Metals & Mining', 'symbol': 'NMDC.NS'},
    {'industry': 'Power', 'symbol': 'NTPCGREEN.NS'},
    {'industry': 'Power', 'symbol': 'NTPC.NS'},
    {'industry': 'Realty', 'symbol': 'OBEROIRLTY.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'symbol': 'ONGC.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'symbol': 'OIL.NS'},
    {'industry': 'Consumer Discretionary', 'symbol': 'OLAELEC.NS'},
    {'industry': 'Financial Services', 'symbol': 'PAYTM.NS'},
    {'industry': 'Information Technology', 'symbol': 'OFSS.NS'},
    {'industry': 'Chemicals', 'symbol': 'PIIND.NS'},
    {'industry': 'Textiles', 'symbol': 'PAGEIND.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'PATANJALI.NS'},
    {'industry': 'Financial Services', 'symbol': 'POLICYBZR.NS'},
    {'industry': 'Information Technology', 'symbol': 'PERSISTENT.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'symbol': 'PETRONET.NS'},
    {'industry': 'Consumer Discretionary', 'symbol': 'PWL.NS'},
    {'industry': 'Chemicals', 'symbol': 'PIDILITIND.NS'},
    {'industry': 'Financial Services', 'symbol': 'PINELABS.NS'},
    {'industry': 'Financial Services', 'symbol': 'PIRAMALFIN.NS'},
    {'industry': 'Capital Goods', 'symbol': 'POLYCAB.NS'},
    {'industry': 'Financial Services', 'symbol': 'PFC.NS'},
    {'industry': 'Power', 'symbol': 'POWERGRID.NS'},
    {'industry': 'Capital Goods', 'symbol': 'PREMIERENE.NS'},
    {'industry': 'Realty', 'symbol': 'PRESTIGE.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'OLECTRA.NS'},
    {'industry': 'Financial Services', 'symbol': 'PNB.NS'},
    {'industry': 'Construction', 'symbol': 'RVNL.NS'},
    {'industry': 'Financial Services', 'symbol': 'RECLTD.NS'},
    {'industry': 'Consumer Discretionary', 'symbol': 'TRAVELFOOD.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'symbol': 'RELIANCE.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'MOTHERSON.NS'},
    {'industry': 'Financial Services', 'symbol': 'SBICARD.NS'},
    {'industry': 'Financial Services', 'symbol': 'SBILIFE.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'SCHAEFFLER.NS'},
    {'industry': 'Construction Materials', 'symbol': 'SHREECEM.NS'},
    {'industry': 'Financial Services', 'symbol': 'SHRIRAMFIN.NS'},
    {'industry': 'Capital Goods', 'symbol': 'ENRIN.NS'},
    {'industry': 'Capital Goods', 'symbol': 'SIEMENS.NS'},
    {'industry': 'Power', 'symbol': 'SJVN.NS'},
    {'industry': 'Chemicals', 'symbol': 'SOLARINDS.NS'},
    {'industry': 'Consumer Discretionary', 'symbol': 'SONACOMS.NS'},
    {'industry': 'Chemicals', 'symbol': 'SRF.NS'},
    {'industry': 'Financial Services', 'symbol': 'STARHEALTH.NS'},
    {'industry': 'Financial Services', 'symbol': 'SBIN.NS'},
    {'industry': 'Metals & Mining', 'symbol': 'SAIL.NS'},
    {'industry': 'Healthcare', 'symbol': 'SUNPHARMA.NS'},
    {'industry': 'Consumer Discretionary', 'symbol': 'SUNTV.NS'},
    {'industry': 'Capital Goods', 'symbol': 'SUPREMEIND.NS'},
    {'industry': 'Capital Goods', 'symbol': 'SUZLON.NS'},
    {'industry': 'Consumer Services', 'symbol': 'SWIGGY.NS'},
    {'industry': 'Financial Services', 'symbol': 'TATACAP.NS'},
    {'industry': 'Telecommunication', 'symbol': 'TATACOMM.NS'},
    {'industry': 'Information Technology', 'symbol': 'TCS.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'TATACONSUM.NS'},
    {'industry': 'Information Technology', 'symbol': 'TATAELXSI.NS'},
    {'industry': 'Capital Goods', 'symbol': 'TMCV.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'TMPV.NS'},
    {'industry': 'Power', 'symbol': 'TATAPOWER.NS'},
    {'industry': 'Metals & Mining', 'symbol': 'TATASTEEL.NS'},
    {'industry': 'Information Technology', 'symbol': 'TATATECH.NS'},
    {'industry': 'Information Technology', 'symbol': 'TECHM.NS'},
    {'industry': 'Financial Services', 'symbol': 'NIACL.NS'},
    {'industry': 'Realty', 'symbol': 'PHOENIXLTD.NS'},
    {'industry': 'Commodities', 'symbol': 'RAMCOCEM.NS'},
    {'industry': 'Capital Goods', 'symbol': 'THERMAX.NS'},
    {'industry': 'Consumer Durables', 'symbol': 'TITAN.NS'},
    {'industry': 'Healthcare', 'symbol': 'TORNTPHARM.NS'},
    {'industry': 'Power', 'symbol': 'TORNTPOWER.NS'},
    {'industry': 'Consumer Services', 'symbol': 'TRENT.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'TIINDIA.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'TVSMOTOR.NS'},
    {'industry': 'Financial Services', 'symbol': 'UCOBANK.NS'},
    {'industry': 'Construction Materials', 'symbol': 'ULTRACEMCO.NS'},
    {'industry': 'Financial Services', 'symbol': 'UNIONBANK.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'UBL.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'UNITDSPR.NS'},
    {'industry': 'Automobile and Auto Components', 'symbol': 'UNOMINDA.NS'},
    {'industry': 'Chemicals', 'symbol': 'UPL.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'symbol': 'VBL.NS'},
    {'industry': 'Consumer Discretionary', 'symbol': 'MANYAVAR.NS'},
    {'industry': 'Consumer Services', 'symbol': 'VMM.NS'},
    {'industry': 'Telecommunication', 'symbol': 'IDEA.NS'},
    {'industry': 'Consumer Durables', 'symbol': 'VOLTAS.NS'},
    {'industry': 'Capital Goods', 'symbol': 'WAAREEENER.NS'},
    {'industry': 'Consumer Discretionary', 'symbol': 'WHIRLPOOL.NS'},
    {'industry': 'Information Technology', 'symbol': 'WIPRO.NS'},
    {'industry': 'Financial Services', 'symbol': 'YESBANK.NS'},
    {'industry': 'Healthcare', 'symbol': 'ZYDUSLIFE.NS'},
]

# --- end ticker universe ---
