"""Quality momentum universe (~130 names).

Edit ``tickers`` below to add/remove symbols. Used by quality momentum scripts and stock RRG.
"""

KEY = "quality"
LABEL = "Quality 130"
DESCRIPTION = "Nifty 100 Quality 30 + Midcap 150 Quality 50 + Smallcap 250 Quality 50"
BENCHMARK_NSE = "Nifty 500"

DEFAULT_VISIBLE = {
    "TCS",
    "INFY",
    "HCLTECH",
    "WIPRO",
    "HINDUNILVR",
    "ITC",
    "NESTLEIND",
    "MARUTI",
    "BAJAJ-AUTO",
    "EICHERMOT",
    "DIVISLAB",
    "DRREDDY",
    "ABB",
    "BEL",
    "HAL",
    "COALINDIA",
    "ASIANPAINT",
    "HAVELLS",
    "PIDILITIND",
    "DIXON",
    "POLYCAB",
}

# --- Ticker universe
tickers = [
    {'industry': 'Capital Goods', 'marketcap': 'Largecap', 'symbol': 'ABB.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Largecap', 'symbol': 'ASIANPAINT.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Largecap', 'symbol': 'BAJAJ-AUTO.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Largecap', 'symbol': 'BEL.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Largecap', 'symbol': 'BOSCHLTD.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Largecap', 'symbol': 'BRITANNIA.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Largecap', 'symbol': 'COALINDIA.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Largecap', 'symbol': 'DIVISLAB.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Largecap', 'symbol': 'DRREDDY.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Largecap', 'symbol': 'EICHERMOT.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Largecap', 'symbol': 'GODREJCP.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Largecap', 'symbol': 'HCLTECH.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Largecap', 'symbol': 'HAVELLS.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Largecap', 'symbol': 'HAL.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Largecap', 'symbol': 'HINDUNILVR.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Largecap', 'symbol': 'HINDZINC.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Largecap', 'symbol': 'ITC.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Largecap', 'symbol': 'INFY.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Largecap', 'symbol': 'LTM.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Largecap', 'symbol': 'MARUTI.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Largecap', 'symbol': 'MAZDOCK.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Largecap', 'symbol': 'NESTLEIND.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Largecap', 'symbol': 'PIDILITIND.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Largecap', 'symbol': 'SOLARINDS.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Largecap', 'symbol': 'TCS.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Largecap', 'symbol': 'TECHM.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Largecap', 'symbol': 'UNITDSPR.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Largecap', 'symbol': 'VBL.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Largecap', 'symbol': 'WIPRO.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Largecap', 'symbol': 'ZYDUSLIFE.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': '360ONE.NS'},
    {'industry': 'Diversified', 'marketcap': 'Midcap', 'symbol': '3MINDIA.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'AIAENG.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'APLAPOLLO.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'ABBOTINDIA.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'AJANTPHARM.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'ALKEM.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'APARINDS.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'ASTRAL.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'BALKRISIND.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'MAHABANK.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Midcap', 'symbol': 'BERGEPAINT.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'BDL.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'CRISIL.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'COFORGE.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Midcap', 'symbol': 'COLPAL.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Midcap', 'symbol': 'COROMANDEL.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'CUMMINSIND.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Midcap', 'symbol': 'DIXON.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'GLAXO.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Midcap', 'symbol': 'GODFRYPHLP.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Midcap', 'symbol': 'GUJGASLTD.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'HDFCAMC.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'HEROMOTOCO.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'HONAUT.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Midcap', 'symbol': 'IRCTC.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Midcap', 'symbol': 'IGL.NS'},
    {'industry': 'Textiles', 'marketcap': 'Midcap', 'symbol': 'KPRMILL.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'KEI.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'KPITTECH.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'LTTS.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Midcap', 'symbol': 'MARICO.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'MOTILALOFS.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'MPHASIS.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'MUTHOOTFIN.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Midcap', 'symbol': 'NMDC.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Midcap', 'symbol': 'NAM-INDIA.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'OFSS.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Midcap', 'symbol': 'PIIND.NS'},
    {'industry': 'Textiles', 'marketcap': 'Midcap', 'symbol': 'PAGEIND.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'PERSISTENT.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Midcap', 'symbol': 'PETRONET.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'POLYCAB.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Midcap', 'symbol': 'PGHH.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'SCHAEFFLER.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'SONACOMS.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Midcap', 'symbol': 'SUPREMEIND.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Midcap', 'symbol': 'SYNGENE.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Midcap', 'symbol': 'TATAELXSI.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Midcap', 'symbol': 'TIINDIA.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'ACE.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'ABSLAMC.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'AFFLE.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'ARE&M.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'ANGELONE.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'APTUS.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'BLS.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'BAYERCROP.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'BSOFT.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'MAPMYINDIA.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'CANFINHOME.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Smallcap', 'symbol': 'CASTROLIND.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'CDSL.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'CHAMBLFERT.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'CLEAN.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'CAMS.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'CYIENT.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'LALPATHLAB.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'ELGIEQUIP.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'EMAMILTD.NS'},
    {'industry': 'Construction', 'marketcap': 'Smallcap', 'symbol': 'ENGINERSIN.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'FINCABLES.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'GILLETTE.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'GPIL.NS'},
    {'industry': 'Metals & Mining', 'marketcap': 'Smallcap', 'symbol': 'GRAVITA.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Smallcap', 'symbol': 'GSPL.NS'},
    {'industry': 'Consumer Services', 'marketcap': 'Smallcap', 'symbol': 'INDIAMART.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'IEX.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'JBCHEPHARM.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Smallcap', 'symbol': 'JSWDULUX.NS'},
    {'industry': 'Consumer Durables', 'marketcap': 'Smallcap', 'symbol': 'KAJARIACER.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'KARURVYSYA.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'KIRLOSBROS.NS'},
    {'industry': 'Fast Moving Consumer Goods', 'marketcap': 'Smallcap', 'symbol': 'LTFOODS.NS'},
    {'industry': 'Oil Gas & Consumable Fuels', 'marketcap': 'Smallcap', 'symbol': 'MGL.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'METROPOLIS.NS'},
    {'industry': 'Automobile and Auto Components', 'marketcap': 'Smallcap', 'symbol': 'MSUMI.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'PFIZER.NS'},
    {'industry': 'Healthcare', 'marketcap': 'Smallcap', 'symbol': 'POLYMED.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'PRAJIND.NS'},
    {'industry': 'Construction', 'marketcap': 'Smallcap', 'symbol': 'RITES.NS'},
    {'industry': 'Telecommunication', 'marketcap': 'Smallcap', 'symbol': 'RAILTEL.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'SONATSOFTW.NS'},
    {'industry': 'Chemicals', 'marketcap': 'Smallcap', 'symbol': 'SUMICHEM.NS'},
    {'industry': 'Media Entertainment & Publication', 'marketcap': 'Smallcap', 'symbol': 'SUNTV.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'TIMKEN.NS'},
    {'industry': 'Capital Goods', 'marketcap': 'Smallcap', 'symbol': 'TRITURBINE.NS'},
    {'industry': 'Financial Services', 'marketcap': 'Smallcap', 'symbol': 'UTIAMC.NS'},
    {'industry': 'Information Technology', 'marketcap': 'Smallcap', 'symbol': 'ZENSARTECH.NS'},
    {'industry': 'Services', 'marketcap': 'Smallcap', 'symbol': 'ECLERX.NS'},
]

# --- end ticker universe ---
