"""India-listed NSE ETFs.

Edit ``tickers``, ``ETF_TO_NSE_INDEX``, and ``ETF_LABELS`` here.
Used by momentum ETF scripts, ETF RRG (etf_rrg_universe.py), and RRGIndicatorEtfs.py.
"""

KEY = "india"
LABEL = "India NSE ETFs"
DESCRIPTION = "NSE-listed sector, thematic, and commodity ETFs"
BENCHMARK_NSE = "Nifty 500"

DEFAULT_VISIBLE = {
    'AUTOBEES.NS',
    'BANKBEES.NS',
    'CHEMICAL.NS',
    'CONSUMBEES.NS',
    'FMCGIETF.NS',
    'GOLDBEES.NS',
    'GROWWRAIL.NS',
    'HEALTHIETF.NS',
    'INFRABEES.NS',
    'ITBEES.NS',
    'MAFANG.NS',
    'METALIETF.NS',
    'MOCAPITAL.NS',
    'MODEFENCE.NS',
    'MOENERGY.NS',
    'MON100.NS',
    'MOREALTY.NS',
    'MOTOUR.NS',
    'OILIETF.NS',
    'PHARMABEES.NS',
    'PSUBNKBEES.NS',
    'PVTBANIETF.NS',
}

tickers = [
    'ALPHA.NS',
    'AUTOBEES.NS',
    'BANKBEES.NS',
    'CONSUMBEES.NS',
    'CPSEETF.NS',
    'MOENERGY.NS',
    'FMCGIETF.NS',
    'GOLDBEES.NS',
    'GROWWPOWER.NS',
    'GROWWRAIL.NS',
    'HDFCSML250.NS',
    'HEALTHIETF.NS',
    'HNGSNGBEES.NS',
    'ICICIB22.NS',
    'INFRABEES.NS',
    'ITBEES.NS',
    'LIQUIDCASE.NS',
    'MAFANG.NS',
    'MAHKTECH.NS',
    'METALIETF.NS',
    'MIDCAPETF.NS',
    'MOCAPITAL.NS',
    'MODEFENCE.NS',
    'MON100.NS',
    'MOREALTY.NS',
    'MOTOUR.NS',
    'MOVALUE.NS',
    'NEXT50IETF.NS',
    'NIFTYBEES.NS',
    'OILIETF.NS',
    'PHARMABEES.NS',
    'PSUBNKBEES.NS',
    'PVTBANIETF.NS',
    'MOMIDMTM.NS',
    'SILVERBEES.NS',
    'SMALLCAP.NS',
    'CHEMICAL.NS',
    'GROWWNET.NS',
]

ETF_TO_NSE_INDEX = {
    'ALPHA.NS': 'Nifty Alpha 50',
    'AUTOBEES.NS': 'Nifty Auto',
    'BANKBEES.NS': 'Nifty Bank',
    'CONSUMBEES.NS': 'Nifty India Consumption',
    'CPSEETF.NS': 'Nifty CPSE',
    'MOENERGY.NS': 'Nifty Energy',
    'FMCGIETF.NS': 'Nifty FMCG',
    'GOLDBEES.NS': None,
    'GROWWPOWER.NS': None,
    'GROWWRAIL.NS': 'Nifty India Railways PSU',
    'HDFCSML250.NS': 'Nifty Smallcap 250',
    'HEALTHIETF.NS': 'Nifty Healthcare Index',
    'HNGSNGBEES.NS': None,
    'ICICIB22.NS': None,
    'INFRABEES.NS': 'Nifty Infrastructure',
    'ITBEES.NS': 'Nifty IT',
    'LIQUIDCASE.NS': None,
    'MAFANG.NS': None,
    'MAHKTECH.NS': None,
    'METALIETF.NS': 'Nifty Metal',
    'MIDCAPETF.NS': 'Nifty Midcap 150',
    'MOCAPITAL.NS': 'Nifty Capital Markets',
    'MODEFENCE.NS': 'Nifty India Defence',
    'MON100.NS': None,
    'MOREALTY.NS': 'Nifty Realty',
    'MOTOUR.NS': 'Nifty India Tourism',
    'MOVALUE.NS': 'NIFTY500 Value 50',
    'NEXT50IETF.NS': 'Nifty Next 50',
    'NIFTYBEES.NS': 'Nifty 50',
    'OILIETF.NS': 'Nifty Oil & Gas',
    'PHARMABEES.NS': 'Nifty Pharma',
    'PSUBNKBEES.NS': 'Nifty PSU Bank',
    'PVTBANIETF.NS': 'Nifty Private Bank',
    'MOMIDMTM.NS': 'Nifty Midcap150 Momentum 50',
    'SILVERBEES.NS': None,
    'SMALLCAP.NS': 'Nifty Smallcap 250 Momentum Quality 100',
    'CHEMICAL.NS': 'Nifty Chemicals',
    'GROWWNET.NS': 'Nifty India Internet',
}

ETF_LABELS = {
    'GOLDBEES.NS': 'Gold ETF',
    'SILVERBEES.NS': 'Silver ETF',
    'MAFANG.NS': 'US FANG+ ETF',
    'MON100.NS': 'Nasdaq 100 ETF',
    'MAHKTECH.NS': 'Hang Seng Tech ETF',
    'HNGSNGBEES.NS': 'Hang Seng ETF',
    'LIQUIDCASE.NS': 'Liquid ETF',
    'ICICIB22.NS': 'Bharat 22 ETF',
    'GROWWPOWER.NS': 'Power ETF',
}

# --- end ticker universe ---
