"""US-listed ETFs — single source of truth for all US ETF tools.

Edit ``tickers`` and ``ETF_LABELS`` here only. Merged with INDmoney
category screenshots (us_indmoney.py). US scripts import via
``momentum.etf.universes.us_universe`` (calls ``ensure_loaded()`` at startup).
"""

KEY = "us"
LABEL = "US ETFs"
DESCRIPTION = "US sector, thematic, and commodity ETFs on Yahoo Finance"
BENCHMARK_YAHOO = "^GSPC"

DEFAULT_VISIBLE = {
    "SPY",
    "QQQ",
    "XLK",
    "XLF",
    "XLE",
    "XLV",
    "XLI",
    "XLP",
    "IWM",
    "EEM",
    "SOXX",
    "ARKK",
    "EWJ",
    "FXI",
}

tickers = [
    # --- US broad / style ---
    'SPY',
    'VTI',
    'QQQ',
    'QQQM',
    'IWM',
    'DIA',
    'RSP',
    'MDY',
    'SCHX',
    'XLG',
    'MGK',
    'VUG',
    'VTV',
    'IWF',
    'IWD',
    # --- GICS sectors (SPDR) ---
    'XLC',
    'XLY',
    'XLP',
    'XLE',
    'XLF',
    'XLV',
    'XLI',
    'XLB',
    'XLRE',
    'XLK',
    'XLU',
    # --- Sector / industry ---
    'SOXX',
    'XBI',
    'XHB',
    'ITB',
    'XRT',
    'KBE',
    'KRE',
    'XOP',
    'OIH',
    'XES',
    'IYT',
    'IGV',
    'ITA',
    'XPH',
    'XHE',
    'KIE',
    'JETS',
    'PICK',
    'PAVE',
    'IGF',
    # --- Thematic / innovation ---
    'ARKK',
    'ARKG',
    'ARKW',
    'SKYY',
    'CIBR',
    'AIQ',
    'DRAM',
    'THRO',
    'ROBO',
    'ICLN',
    'TAN',
    'GRID',
    'LIT',
    'URA',
    'GUNR',
    'MOO',
    'COPX',
    'REMX',
    'DXYZ',
    # --- International / country ---
    'VXUS',
    'VEA',
    'EFA',
    'EEM',
    'IEMG',
    'VWO',
    'EZU',
    'MCHI',
    'FXI',
    'ASHR',
    'CQQQ',
    'KWEB',
    'EMXC',
    'EWJ',
    'EWY',
    'EWT',
    'EWA',
    'EWC',
    'EWG',
    'EWU',
    'EWUS',
    'EWP',
    'EWH',
    'EWS',
    'EWM',
    'EIS',
    'EZA',
    'EIDO',
    'THD',
    'EPOL',
    'EWW',
    'VNM',
    'ECH',
    'EWL',
    'EWN',
    'EWD',
    'EWI',
    'EWZ',
    'ARGT',
    'TUR',
    'GREK',
    'KSA',
    'FM',
    # 'RSX', will enable in Interactive Brokers IBKR
    # --- Real estate ---
    'IYR',
    # --- Commodities / metals ---
    'GDX',
    'SIL',
    'GSG',
    'DBC',
    'USO',
    'UNG',
    'DBA',
    'WEAT',
    'CORN',
    'CPER',
    'PALL',
    # --- Crypto ---
    'BITO',
    'IBIT',
    'WGMI',
    'ETHA',
    # --- Factor / dividend ---
    'MTUM',
    'QUAL',
    'USMV',
    'VLUE',
    # --- INDmoney: S&P 500 ---
    'SFY',
    # --- INDmoney: Nasdaq 100 ---
    'ONEQ',
    'QQQE',
    # --- INDmoney: Platinum ---
    'PLTM',
    # --- INDmoney: Copper ---
    'ICOP',
    # --- INDmoney: Lithium ---
    'BATT',
    'LITP',
    'ILIT',
    # --- INDmoney: Uranium ---
    'NLR',
    'URNJ',
    'NUKZ',
    # --- INDmoney: Oil & Gas ---
    'FENY',
    'IYE',
    # --- INDmoney: Technology ---
    'IPAY',
    # --- INDmoney: Data Center ---
    'DTCR',
    # --- INDmoney: Europe ---
    'IEV',
    'EWQ',
    'EDEN',
    'IEUS',
    # --- INDmoney: Japan ---
    'SCJ',
    'JPXN',
    # --- INDmoney: Middle East & UAE ---
    'UAE',
    # --- INDmoney: Highest Returns ---
    'KGRN',
    'CNRG',
    'KARS',
    # --- INDmoney: All Weather ---
    'ONEV',
    'FDLO',
    'QLV',
    'LGLV',
    'LVHD',
    'VSMV',
    'HUSV',
    'SMLV',
    'DVOL',
    'SPLV',
    'XMLV',
    'EELV',
    'XSLV',
    'XSHD',
]

ETF_LABELS = {
    "SPY": "SPDR S&P 500 ETF Trust",    
    "VTI": "Total US Market",
    "QQQ": "Invesco QQQ Trust",
    "QQQM": "Invesco NASDAQ 100 ETF",
    "IWM": "Russell 2000",
    "DIA": "Dow 30",
    "RSP": "Invesco S&P 500 Equal Weight ETF",
    "MDY": "S&P MidCap 400",
    "SCHX": "Large-Cap Core",
    "XLG": "Top 50 Mega-Cap",
    "MGK": "Mega-Cap Growth",
    "VUG": "Growth",
    "VTV": "Value",
    "IWF": "Russell 1000 Growth",
    "IWD": "Russell 1000 Value",
    "XLC": "Communication",
    "XLY": "Consumer Disc.",
    "XLP": "Consumer Staples",
    "XLE": "Energy Select Sector SPDR Fund",
    "XLF": "Financials",
    "XLV": "Health Care",
    "XLI": "Industrials",
    "XLB": "Materials",
    "XLRE": "Real Estate",
    "XLK": "Technology Select Sector SPDR Fund",
    "XLU": "Utilities",       
    "SOXX": "iShares Semiconductor ETF",
    "XBI": "Biotech",   
    "XHB": "Homebuilders",
    "ITB": "Home Construction",
    "XRT": "Retail",
    "KBE": "Banks",
    "KRE": "Regional Banks",
    "XOP": "SPDR S&P Oil & Gas Exploration & Production ETF",
    "OIH": "VanEck Oil Services ETF",
    "XES": "Oil & Gas Equipment",
    "IYT": "Transportation",
    "IGV": "Software",
    "ITA": "iShares U.S. Aerospace & Defense ETF",
    "XPH": "Pharma",
    "XHE": "Health Care Equipment",
    "KIE": "Insurance",
    "JETS": "Global Airlines",
    "PICK": "Metals & Mining iShares",
    "PAVE": "US Infrastructure",
    "IGF": "Global Infrastructure",
    "ARKK": "ARK Innovation ETF",
    "ARKG": "ARK Genomics",
    "ARKW": "ARK Next Gen Internet",
    "SKYY": "First Trust Cloud Computing ETF",
    "CIBR": "Cybersecurity",
    "AIQ": "Global X Artificial Intelligence & Technology ETF",
    "DRAM": "Roundhill Memory ETF",
    "THRO": "Thematic Rotation Active",
    "ROBO": "Robo Global Robotics and Automation Index ETF",
    "ICLN": "iShares Global Clean Energy ETF",
    "TAN": "Invesco Solar ETF",
    "GRID": "Smart Grid",
    "LIT": "Global X Lithium & Battery Tech ETF",
    "URA": "Global X Uranium ETF",
    "GUNR": "Natural Resources",
    "MOO": "Agribusiness",
    "COPX": "Global X Copper Miners ETF",
    "REMX": "VanEck Rare Earth/Strategic Metals ETF",
    "DXYZ": "Destiny Tech100",
    "VXUS": "Total International",
    "VEA": "Developed ex-US",
    "EFA": "EAFE",
    "EEM": "Emerging Markets",
    "IEMG": "Core Emerging Markets",
    "VWO": "EM Vanguard",
    "EZU": "iShares MSCI Eurozone ETF",
    "MCHI": "iShares MSCI China ETF",
    "FXI": "iShares China Large-Cap ETF",
    "ASHR": "Xtrackers Harvest CSI 300 China A-Shares ETF",
    "CQQQ": "Invesco China Technology ETF",
    "KWEB": "KraneShares CSI China Internet ETF",
    "EMXC": "EM ex-China",
    "EWJ": "iShares MSCI Japan ETF",
    "EWY": "iShares MSCI South Korea ETF",
    "EWT": "Taiwan",
    "EWA": "Australia",
    "EWC": "Canada",
    "EWG": "iShares MSCI Germany ETF",
    "EWU": "iShares MSCI United Kingdom ETF",
    "EWUS": "Small-Cap UK",
    "EWP": "iShares MSCI Spain ETF",
    "EWH": "Hong Kong",
    "EWS": "Singapore",
    "EWM": "Malaysia",
    "EIS": "iShares MSCI Israel ETF",
    "EZA": "South Africa",
    "EIDO": "Indonesia",
    "THD": "Thailand",
    "EPOL": "Poland",
    "EWW": "Mexico",
    "VNM": "Vietnam",
    "ECH": "Chile",
    "EWL": "iShares MSCI Switzerland ETF",
    "EWN": "iShares MSCI Netherlands ETF",
    "EWD": "Sweden",
    "EWI": "iShares MSCI Italy ETF",
    "EWZ": "Brazil",
    "ARGT": "Argentina",
    "TUR": "Turkey",
    "GREK": "Greece",
    "KSA": "iShares MSCI Saudi Arabia ETF",
    "FM": "Frontier Markets",
    # "RSX": "Russia", will enable in Interactive Brokers IBKR
    "IYR": "Real Estate",
    "GDX": "Gold Miners",
    "SIL": "Silver Miners",
    "GSG": "Commodities iShares",
    "DBC": "Commodities",
    "USO": "United States Oil Fund LP",
    "UNG": "United States Natural Gas Fund LP",
    "DBA": "Agriculture",
    "WEAT": "Wheat",
    "CORN": "Corn",
    "CPER": "United States Copper Index Fund",
    "PALL": "Palladium",
    "BITO": "Bitcoin Strategy",
    "IBIT": "Bitcoin iShares",
    "WGMI": "Bitcoin Miners",
    "ETHA": "Ethereum",
    "MTUM": "Momentum",
    "QUAL": "Quality",
    "USMV": "Min Volatility",
    "VLUE": "Value Factor",
    "SFY": "SoFi Select 500 ETF",
    "ONEQ": "Fidelity Nasdaq Composite Index ETF",
    "QQQE": "Direxion NASDAQ-100 Equal Weighted Index Shares",
    "PLTM": "GraniteShares Platinum Trust",
    "ICOP": "iShares Copper and Metals Mining ETF",
    "BATT": "Amplify Lithium & Battery Technology ETF",
    "LITP": "Sprott Lithium Miners ETF",
    "ILIT": "iShares Lithium Miners and Producers ETF",
    "NLR": "VanEck Uranium+Nuclear Energy ETF",
    "URNJ": "Sprott Junior Uranium Miners ETF",
    "NUKZ": "Range Nuclear Renaissance Index ETF",
    "FENY": "Fidelity MSCI Energy Index ETF",
    "IYE": "iShares U.S. Energy ETF",
    "IPAY": "Amplify Digital Payments ETF",
    "DTCR": "Global X Data Center & Digital Infrastructure ETF",
    "IEV": "iShares Europe ETF",
    "EWQ": "iShares MSCI France ETF",
    "EDEN": "iShares MSCI Denmark ETF",
    "IEUS": "iShares MSCI Europe Small-Cap ETF",
    "SCJ": "iShares MSCI Japan Small-Cap ETF",
    "JPXN": "iShares JPX-Nikkei 400 ETF",
    "UAE": "iShares MSCI UAE ETF",
    "KGRN": "KraneShares MSCI China Clean Technology ETF",
    "CNRG": "SPDR Kensho Clean Power ETF",    
    "KARS": "KraneShares Electric Vehicles and Future Mobility Index ETF",
    "ONEV": "SPDR Russell 1000 Low Volatility Focus ETF",
    "FDLO": "Fidelity Low Volatility Factor ETF",
    "QLV": "FlexShares US Quality Low Volatility Index Fund",
    "LGLV": "SPDR SSGA US Large Cap Low Volatility Index ETF",
    "LVHD": "Legg Mason Low Volatility High Dividend ETF",
    "VSMV": "VictoryShares US Multi-Factor Minimum Volatility ETF",
    "HUSV": "First Trust Horizon Managed Volatility Domestic ETF",
    "SMLV": "SPDR SSGA US Small Cap Low Volatility Index ETF",
    "DVOL": "First Trust Dorsey Wright Momentum & Low Volatility ETF",
    "SPLV": "Invesco S&P 500 Low Volatility ETF",
    "XMLV": "Invesco S&P MidCap Low Volatility ETF",
    "EELV": "Invesco S&P Emerging Markets Low Volatility ETF",
    "XSLV": "Invesco S&P SmallCap Low Volatility ETF",
    "XSHD": "Invesco S&P SmallCap High Dividend Low Volatility ETF",
}

# Near-duplicate tradable ETFs — at most one per bucket in a portfolio.
OVERLAP_BUCKETS: tuple[frozenset[str], ...] = (
    frozenset({"SOXX"}),
    frozenset({"SKYY", "IGV"}),
    frozenset({"CIBR"}),
    frozenset({"XBI"}),
    frozenset({"BITO", "IBIT"}),
    frozenset({"TAN", "ICLN"}),
    frozenset({"FXI", "MCHI"}),
    frozenset({"KWEB", "CQQQ"}),
    frozenset({"GDX"}),
    frozenset({"IYR", "XLRE"}),
)

def overlap_bucket_for(symbol: str) -> frozenset[str] | None:
    bare = (symbol or "").strip().upper()
    for bucket in OVERLAP_BUCKETS:
        if bare in bucket:
            return bucket
    return None


# --- end ticker universe ---
