"""US ETF names from INDmoney category screenshots.

Merged into ``us.py``. Kept for reference and re-merge via ``scripts/merge_indmoney_us.py``.
Leveraged / inverse tickers are under EXCLUDED and are not in the canonical universe.
"""

from __future__ import annotations

# category_key → [(ticker, name), ...]
INDMONEY_CATEGORIES: dict[str, list[tuple[str, str]]] = {
    "S&P 500": [
        ("IVV", "iShares Core S&P 500 ETF"),
        ("VOO", "Vanguard S&P 500 ETF"),
        ("SPY", "SPDR S&P 500 ETF Trust"),
        ("RSP", "Invesco S&P 500 Equal Weight ETF"),
        ("SFY", "SoFi Select 500 ETF"),
    ],
    "Nasdaq 100": [
        ("QQQ", "Invesco QQQ Trust"),
        ("QQQM", "Invesco NASDAQ 100 ETF"),
        ("ONEQ", "Fidelity Nasdaq Composite Index ETF"),
        ("QQQE", "Direxion NASDAQ-100 Equal Weighted Index Shares"),
    ],
    "Platinum": [
        ("PPLT", "abrdn Physical Platinum Shares ETF"),
        ("PLTM", "GraniteShares Platinum Trust"),
    ],
    "Copper": [
        ("ICOP", "iShares Copper and Metals Mining ETF"),
        ("COPX", "Global X Copper Miners ETF"),
        ("CPER", "United States Copper Index Fund"),
    ],
    "Lithium": [
        ("LIT", "Global X Lithium & Battery Tech ETF"),
        ("BATT", "Amplify Lithium & Battery Technology ETF"),
        ("LITP", "Sprott Lithium Miners ETF"),
        ("ILIT", "iShares Lithium Miners and Producers ETF"),
    ],
    "Rare Earth": [
        ("REMX", "VanEck Rare Earth/Strategic Metals ETF"),
        ("SETM", "Sprott Energy Transition Materials ETF"),
    ],
    "Uranium": [
        ("NLR", "VanEck Uranium+Nuclear Energy ETF"),
        ("URA", "Global X Uranium ETF"),
        ("URNM", "Sprott Uranium Miners ETF"),
        ("URNJ", "Sprott Junior Uranium Miners ETF"),
        ("NUKZ", "Range Nuclear Renaissance Index ETF"),
    ],
    "Oil & Gas": [
        ("IEO", "iShares U.S. Oil & Gas Exploration & Production ETF"),
        ("VDE", "Vanguard Energy Index Fund ETF Shares"),
        ("XLE", "Energy Select Sector SPDR Fund"),
        ("XOP", "SPDR S&P Oil & Gas Exploration & Production ETF"),
        ("OIH", "VanEck Oil Services ETF"),
        ("FENY", "Fidelity MSCI Energy Index ETF"),
        ("MLPX", "Global X MLP & Energy Infrastructure ETF"),
        ("LNGX", "Global X U.S. Natural Gas ETF"),
        ("USO", "United States Oil Fund LP"),
        ("IYE", "iShares U.S. Energy ETF"),
    ],
    "Natural Gas": [
        ("UNG", "United States Natural Gas Fund LP"),
        ("FCG", "First Trust Natural Gas ETF"),
        ("LNGX", "Global X U.S. Natural Gas ETF"),
    ],
    "AI": [
        ("ARTY", "iShares Future AI & Tech ETF"),
        ("WTAI", "WisdomTree Artificial Intelligence and Innovation Fund"),
        ("AIQ", "Global X Artificial Intelligence & Technology ETF"),
        ("BOTZ", "Global X Robotics & Artificial Intelligence ETF"),
        ("ARKQ", "ARK Autonomous Technology & Robotics ETF"),
        ("CHAT", "Roundhill Generative AI & Technology ETF"),
        ("AIEQ", "Amplify AI Powered Equity ETF"),
        ("ROBO", "Robo Global Robotics and Automation Index ETF"),
        ("THNQ", "Robo Global Artificial Intelligence ETF"),
        ("IVES", "Dan IVES Wedbush AI Revolution ETF"),
        ("IGPT", "Invesco AI and Next Gen Software ETF"),
    ],
    "Technology": [
        ("VGT", "Vanguard Information Technology Index Fund ETF Shares"),
        ("XLK", "Technology Select Sector SPDR Fund"),
        ("ARKK", "ARK Innovation ETF"),
        ("IYW", "iShares U.S. Technology ETF"),
        ("FTEC", "Fidelity MSCI Information Technology Index ETF"),
        ("IGM", "iShares Expanded Tech Sector ETF"),
        ("XT", "iShares Exponential Technologies ETF"),
        ("TDIV", "First Trust NASDAQ Technology Dividend Index Fund"),
        ("QTEC", "First Trust NASDAQ-100-Technology Sector Index Fund"),
        ("ROBO", "Robo Global Robotics and Automation Index ETF"),
        ("FXL", "First Trust Technology AlphaDEX Fund"),
        ("IPAY", "Amplify Digital Payments ETF"),
        ("BLOK", "Amplify Transformational Data Sharing ETF"),
        ("XNTK", "SPDR Morgan Stanley Technology"),
    ],
    "Semiconductor": [
        ("SOXX", "iShares Semiconductor ETF"),
        ("SOXQ", "Invesco PHLX Semiconductor ETF"),
        ("FTXL", "First Trust Nasdaq Semiconductor ETF"),
        ("SMH", "VanEck Semiconductor ETF"),
        ("XSD", "SPDR S&P Semiconductor ETF"),
        ("DRAM", "Roundhill Memory ETF"),
        ("PSI", "Invesco Dynamic Semiconductors ETF"),
        ("SEMI", "Columbia Seligman Semiconductor & Technology ETF"),
        ("SHOC", "Strive U.S. Semiconductor ETF"),
        ("CHPS", "Xtrackers Semiconductor Select Equity ETF"),
    ],
    "Data Center": [
        ("DTCR", "Global X Data Center & Digital Infrastructure ETF"),
        ("CLOU", "Global X Cloud Computing ETF"),
        ("SRVR", "Pacer Benchmark Data & Infrastructure Real Estate SCTR ETF"),
        ("SKYY", "First Trust Cloud Computing ETF"),
    ],
    "Aerospace & Defence": [
        ("ITA", "iShares U.S. Aerospace & Defense ETF"),
        ("XAR", "SPDR S&P Aerospace & Defense ETF"),
        ("PPA", "Invesco Aerospace & Defense ETF"),
        ("SHLD", "Global X Defense Tech ETF"),
        ("FITE", "SPDR S&P Kensho Future Security ETF"),
        ("UFO", "Procure Space ETF"),
        ("NASA", "Tema Space Innovators ETF"),
    ],
    "China": [
        ("CNYA", "iShares MSCI China A ETF"),
        ("FXI", "iShares China Large-Cap ETF"),
        ("MCHI", "iShares MSCI China ETF"),
        ("GXC", "SPDR S&P China ETF"),
        ("CQQQ", "Invesco China Technology ETF"),
        ("CNXT", "VanEck ChiNext ETF"),
        ("ASHR", "Xtrackers Harvest CSI 300 China A-Shares ETF"),
        ("KWEB", "KraneShares CSI China Internet ETF"),
        ("CXSE", "WisdomTree China ex-State-Owned Enterprises Fund"),
        ("PGJ", "Invesco Golden Dragon China ETF"),
    ],
    "Europe": [
        ("EZU", "iShares MSCI Eurozone ETF"),
        ("EWU", "iShares MSCI United Kingdom ETF"),
        ("IEV", "iShares Europe ETF"),
        ("IEUR", "iShares Core MSCI Europe ETF"),
        ("EWG", "iShares MSCI Germany ETF"),
        ("VGK", "Vanguard FTSE Europe Index Fund ETF Shares"),
        ("FEZ", "State Street SPDR EURO STOXX 50 ETF"),
        ("HEDJ", "WisdomTree Europe Hedged Equity Fund"),
        ("EWQ", "iShares MSCI France ETF"),
        ("EWL", "iShares MSCI Switzerland ETF"),
        ("EWI", "iShares MSCI Italy ETF"),
        ("EWP", "iShares MSCI Spain ETF"),
        ("EWN", "iShares MSCI Netherlands ETF"),
        ("EDEN", "iShares MSCI Denmark ETF"),
        ("IEUS", "iShares MSCI Europe Small-Cap ETF"),
    ],
    "Japan": [
        ("HEWJ", "iShares Currency Hedged MSCI Japan ETF"),
        ("EWJ", "iShares MSCI Japan ETF"),
        ("BBJP", "JPMorgan BetaBuilders Japan ETF"),
        ("DXJ", "WisdomTree Japan Hedged Equity Fund"),
        ("FLJP", "Franklin FTSE Japan ETF"),
        ("DBJP", "Xtrackers MSCI Japan Hedged Equity ETF"),
        ("SCJ", "iShares MSCI Japan Small-Cap ETF"),
        ("JPXN", "iShares JPX-Nikkei 400 ETF"),
        ("FJP", "First Trust Japan AlphaDEX Fund"),
    ],
    "South Korea": [
        ("EWY", "iShares MSCI South Korea ETF"),
        ("FLKR", "Franklin FTSE South Korea ETF"),
    ],
    "Middle East & UAE": [
        ("UAE", "iShares MSCI UAE ETF"),
        ("KSA", "iShares MSCI Saudi Arabia ETF"),
        ("QAT", "iShares MSCI Qatar ETF"),
        ("KWT", "iShares MSCI Kuwait ETF"),
        ("EIS", "iShares MSCI Israel ETF"),
    ],
    "Highest Returns": [
        ("LIT", "Global X Lithium & Battery Tech ETF"),
        ("TAN", "Invesco Solar ETF"),
        ("QCLN", "First Trust NASDAQ Clean Edge Green Energy Index Fund"),
        ("UNL", "United States 12 Month Natural Gas Fund LP"),
        ("KGRN", "KraneShares MSCI China Clean Technology ETF"),
        ("CNRG", "SPDR Kensho Clean Power ETF"),
        ("UGA", "United States Gasoline Fund LP"),
        ("REMX", "VanEck Rare Earth/Strategic Metals ETF"),
        ("SMH", "VanEck Semiconductor ETF"),
        ("FCG", "First Trust Natural Gas ETF"),
        ("SMOG", "VanEck Low Carbon Energy ETF"),
        ("PSI", "Invesco Dynamic Semiconductors ETF"),
        ("SOXX", "iShares Semiconductor ETF"),
        ("KARS", "KraneShares Electric Vehicles and Future Mobility Index ETF"),
        ("XSD", "SPDR S&P Semiconductor ETF"),
        ("URA", "Global X Uranium ETF"),
        ("DBE", "Invesco DB Energy Fund"),
        ("ICLN", "iShares Global Clean Energy ETF"),
    ],
    "All Weather": [
        ("ONEV", "SPDR Russell 1000 Low Volatility Focus ETF"),
        ("FDLO", "Fidelity Low Volatility Factor ETF"),
        ("QLV", "FlexShares US Quality Low Volatility Index Fund"),
        ("LGLV", "SPDR SSGA US Large Cap Low Volatility Index ETF"),
        ("LVHD", "Legg Mason Low Volatility High Dividend ETF"),
        ("VSMV", "VictoryShares US Multi-Factor Minimum Volatility ETF"),
        ("HUSV", "First Trust Horizon Managed Volatility Domestic ETF"),
        ("SMLV", "SPDR SSGA US Small Cap Low Volatility Index ETF"),
        ("DVOL", "First Trust Dorsey Wright Momentum & Low Volatility ETF"),
        ("SPHD", "Invesco S&P 500 High Dividend Low Volatility ETF"),
        ("SPLV", "Invesco S&P 500 Low Volatility ETF"),
        ("LVHI", "Franklin International Low Volatility High Dividend Index ETF"),
        ("XMLV", "Invesco S&P MidCap Low Volatility ETF"),
        ("DIV", "Global X SuperDividend U.S. ETF"),
        ("EELV", "Invesco S&P Emerging Markets Low Volatility ETF"),
        ("XSLV", "Invesco S&P SmallCap Low Volatility ETF"),
        ("XSHD", "Invesco S&P SmallCap High Dividend Low Volatility ETF"),
    ],
}

# From same screenshots — do not add to final universe (leveraged / inverse).
INDMONEY_EXCLUDED: dict[str, list[tuple[str, str]]] = {
    "S&P 500": [
        ("UPRO", "ProShares UltraPro S&P500"),
        ("SPXL", "Direxion Daily S&P 500 Bull 3X Shares"),
        ("SPXS", "Direxion Daily S&P 500 Bear 3X Shares"),
        ("SPDN", "Direxion Daily S&P 500 Bear 1X Shares"),
    ],
    "Nasdaq 100": [
        ("TQQQ", "ProShares UltraPro QQQ"),
        ("SQQQ", "ProShares UltraPro Short QQQ"),
    ],
    "Oil & Gas": [
        ("OILU", "MicroSectors Oil & Gas Exploration & Production 3X Leveraged ETNs"),
        ("DRIP", "Direxion Daily S&P Oil & Gas Exp. & Prod. Bear 2X Shares"),
        ("GUSH", "Direxion Daily S&P Oil & Gas Exp. & Prod. Bull 2X Shares"),
        ("UCO", "ProShares Ultra Bloomberg Crude Oil"),
        ("SCO", "ProShares UltraShort Bloomberg Crude Oil"),
    ],
    "Natural Gas": [
        ("BOIL", "ProShares Ultra Bloomberg Natural Gas"),
        ("KOLD", "ProShares UltraShort Bloomberg Natural Gas"),
    ],
    "Technology": [
        ("ROM", "ProShares Ultra Technology"),
    ],
    "Semiconductor": [
        ("USD", "ProShares Ultra Semiconductors"),
        ("SOXS", "Direxion Daily Semiconductor Bear 3X Shares"),
        ("SOXL", "Direxion Daily Semiconductor Bull 3X Shares"),
    ],
    "Aerospace & Defence": [
        ("DFEN", "Direxion Daily Aerospace & Defense Bull 3X Shares"),
    ],
    "China": [
        ("YINN", "Direxion Daily FTSE China Bull 3X Shares"),
        ("YANG", "Direxion Daily FTSE China Bear 3X Shares"),
    ],
    "Japan": [
        ("EZJ", "ProShares Ultra MSCI Japan"),
        ("EWV", "ProShares UltraShort MSCI Japan"),
    ],
    "South Korea": [
        ("KORU", "Direxion Daily South Korea Bull 3X Shares"),
    ],
}
