name: Update US ETF Momentum to GSheet

on:
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Libraries
        run: pip install dotenv matplotlib pandas pyotp requests rich scipy yfinance gspread oauth2client

      - name: Run US ETF Momentum Script
        env:
          ETF_MOMENTUM_CREDENTIAL: ${{ secrets.ETF_MOMENTUM_CREDENTIAL }}
        run: python momentum/etf/etf_us_momentum_sheet_updater.py
