name: Update IN ETF Momentum to GSheet

on:
  schedule:
    # 08:30 UTC = 14:00 IST
    - cron: '30 8 * * 1-5'
    # 09:00 UTC = 14:30 IST
    - cron: '0 9 * * 1-5'
    # 09:30 UTC = 15:00 IST
    - cron: '30 9 * * 1-5'
    # 09:45 UTC = 15:15 IST
    - cron: '45 9 * * 1-5'
  workflow_dispatch:

jobs:
  update-in-etf-momentum-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Libraries
        run: pip install dotenv matplotlib pandas pyotp requests rich scipy yfinance gspread oauth2client

      - name: Run ETF Momentum Script
        env:
          # GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          ETF_MOMENTUM_CREDENTIAL: ${{ secrets.ETF_MOMENTUM_CREDENTIAL }}
        run: python momentum/etf/etf_momentum_sheet_updater.py
